### ISSUE TITLE
Webhook response: 413 Payload Too Large

### ISSUE THREAD

**Issue by punkstar** [backstrokeapp/server#6]
I have the web hook configured on a repository but there's an error 413 in my "Recent Deliveries".  The full output from the request and response, headers and body, can be found on this gist: https://gist.github.com/punkstar/405e8d684aa7bc733e5cdc3bbca3dad4

![screenshot](https://cloud.githubusercontent.com/assets/179072/17296329/922d31a4-57f8-11e6-8e82-dc3ae97af77c.png)

**Comment by 1egoman** [comment]
@punkstar Hmm, that's interesting. I'm guessing that a 413 is being raised because the request body is so long. I'll try and verify on my end, but could you attempt the a similar push with a smaller body (ie, with a smaller commit?)

Thanks for providing all the detail, it really makes my life a lot easier. :smile:

**Comment by sparkoo** [comment]
Same issue here. Any progress on this? Thanks!

**Comment by 1egoman** [comment]
@sparkoo @punkstar Yea, I think I figured this out. The problem is that Github makes webhook responses so large that express's body parser can occasionally choke and throw this. It isn't really anything I can fix (the error is thrown by `body-parser`, not me).

In fact, this issue is part of the reason I've been developing v2 of Backstroke. It you'd like to check it out, it's at https://backstroke.us.Keep in mind it's very beta.

**Comment by 1egoman** [comment]
Should be fixed by https://github.com/backstrokeapp/server/issues/66, I think.
