### ISSUE TITLE
Not syncing automatically 

### ISSUE THREAD

**Issue by shikhir-arora** [backstrokeapp/server#99]
Hi there! 

Backstroke has been working well for me, but over the last week or so I've noticed it has stopped syncing automatically and I have to either resync or run the manual webhook link for it to update.

It seemed to be fine after #98 - and was for a while, but suddenly stopped working over the past week or so.

**Comment by 1egoman** [comment]
I see what's going on - looks like the server that Backstroke is running on has run out of ram (and the job that does the automatic syncing is being OOMed). Unfortunately, I'm still away and don't have a solid internet connection (which I need in order to scale up the server instance to alleviate this problem). I should have a solid connection hopefully later tonight but if not then later this week and then I can perform the upgrade. Sorry for the delayed response, things always have a tendency to break at the worst possible time!

**Comment by 1egoman** [comment]
I finally have a stable internet connection again and was able to perform a ram upgrade on the digitalocean droplet powering Backstroke. Again, very sorry about this but hopefully the service should be running again.

**Comment by shikhir-arora** [comment]
Thanks!
